### ISSUE TITLE
telemetry logstash instance failed to collect stream from MDT configuration

### ISSUE THREAD

**Issue by zoubazouba** [cisco/logstash-codec-bigmuddy-network-telemetry#4]
Hello,

I am facing this logstash error : 
 logstash.inputs.tcp - An error occurred. Closing connection {:client=>"*******":59523", :exception=>#<NameError: uninitialized constant LogStash::Codecs::Telemetry::Telemetry>, :backtrace=>["org/jruby/RubyModule.java:2719:in `const_missing'", "/cisco-telemetry-plugin/lib/logstash/codecs/telemetry.rb:739:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:182:in `handle_socket'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:153:in `server_connection_thread'"]}

my configuration file : 
input {
    tcp {
        port => 5551
        codec => telemetry {
           mdt => true
           protofiles => "/data/proto"
             }
}
}
output {
        elasticsearch {
            hosts => "elasticsearch:9200"
            index => "telemetry-gpb-%{+YYYY.MM.dd}"
        }
}

One more information is that I am using this plugin with logstash 5.3.0 and it worked using json codec and PDT configuration on the router.

Best,

**Comment by n33raj116** [comment]
I got the same error. Have you been able to solve it @zoubazouba  ???

**Comment by hunjuice** [comment]
I am getting the same error? Did you ever get it fixed?

**Comment by ScXin610** [comment]
I finish the configuration for collecting MDT data, but decode error, are you successful to collect?
